version: 2
jobs:
  test:
    docker:
      - image: circleci/node:13.14.0
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: node splitStringIntoChunks.test.js
      - run: yarn test:coverage
      - run:
          name: Generate coveralls config
          command: "echo repo_token: $COVERALLS_REPO_TOKEN > ./.coveralls.yml"
      - run:
          name: Upload coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
