version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/app
    steps:
      - checkout
      - run: node splitStringIntoChunks.test.js


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
