version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:13.14.0
    working_directory: ~/app

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn danger ci --failOnErrors
      - run: yarn lint
      - run: node splitStringIntoChunks.test.js
      - run: yarn test:coverage
      - persist_to_workspace:
          root: ~/app
          paths:
            - .git
            - node_modules
            - coverage
  upload_coverage:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/app
      - run: git checkout .
      - run:
          name: Generate coveralls config
          command: "echo repo_token: $COVERALLS_REPO_TOKEN > ./.coveralls.yml"
      - run:
          name: Upload coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - upload_coverage:
          requires:
            - test
          filters:
            branches:
              only:
                - master
