version: 2
jobs:
  test:
    docker:
      - image: circleci/node:13.10.1
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: yarn lint
      - run: node splitStringIntoChunks.test.js
      - run: yarn test


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
